### ISSUE TITLE
Rehaul how comments are attached

### ISSUE THREAD

**Issue by jlongster** [jlongster/prettier#275]
Opening this bug so we can dupe any existing bug about comments here. I will make a quick todo list, but these may not be individually fixed. Rewriting parts of the comment algorithm will probably fix many of them in one go.

* [x] Trailing comments on opening blocks are moved down (#271)
* [ ] Comments not emitted in chaining calls (#200)
* [x] Comments stripped from empty functions/if/try/etc (basically any block) (#31, #87)
* [x] Trailing comments inside a function call should stay where they are (see various issues in #135)

There is also the checklist of comment issues on nuclide in #135. We should run through that list after my rehaul. I'll pull a few core bugs from there to here.

**Comment by n1k0** [comment]
Dunno if the list covers them but you may want to add an entry for [comments within try/catch blocks](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22try%20%7B%5Cn%20%20%2F%2F%20a%5Cn%7D%20catch%20(e)%20%7B%5Cn%20%20%2F%2F%20b%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Afalse%7D%7D).

**Comment by vjeux** [comment]
@n1k0 Same bug as #31 and #87. #207 is a fix (not the right one) for babylon.

**Comment by jlongster** [comment]
Yep, that's the 3rd one where they are stripped away from empty blocks. It happens with any empty block, no matter what kind of keyword is before it.

**Comment by francois** [comment]
This also happens on empty files, such as Rails' `application.js`:

```javascript
// This is a manifest file that'll be compiled into application.js, which will include all the files
// listed below.
//
// Any JavaScript/Coffee file within this directory, lib/assets/javascripts, vendor/assets/javascripts,
// or any plugin's vendor/assets/javascripts directory can be referenced here using a relative path.
//
// It's not advisable to add code directly here, but if you do, it'll appear at the bottom of the
// compiled file.
//
// Read Sprockets README (https://github.com/rails/sprockets#sprockets-directives) for details
// about supported directives.
//

```

ends up as an empty file. I don't really care about that specific file, because it's empty, but this one has useful content that we would like to keep (`libraries.js`):

```javascript

// 3rd Party libs
// This is optional (in case you have `I18n is not defined` error)
// If you want to put this line, you must put it BEFORE `i18n/translations`
//= require i18n
//
// This is a must
//= require i18n/translations
//= require pusher.min
//= require jquery.min
//= require jquery_ujs
//= require jquery-ui.min
//= require plugins.jquery
//= require momentum.jquery
```

This too is returned as the empty file.

**Comment by vjeux** [comment]
@francois thanks for the report, this is actually not a known bug. Do you mind creating a separate issue so that we can track it down on its own instead of having it in a comment as part of a bigger one? Thanks!

**Comment by jlongster** [comment]
Argh, didn't autoclose, see above PR
